apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "m2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "ms-ssi"
spec:
  source:
    git:
      uri: "https://github.com/ashmitakapoor/ssi"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"